version: '3.8'
services:
  mongodb:
    image: "mongo"
    ports:
      - "27017:27017"
    volumes:
      - data:/data/db
  server:
    build:
      context: ./server
    ports:
      - "5000:5000"
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongodb

  client:
    build:
      context: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules

volumes:
  data:
  logs: